services:
  - type: web
    name: frontend
    env: static # Alternatively, docker if needed
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: /build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_BACKEND1_URL
        value: https://backend1-service.onrender.com
      - key: VITE_BACKEND2_URL
        value: https://backend2-service.onrender.com

  - type: web
    name: backend1
    plan: free
    env: docker
    dockerfilePath: ./backend_1/Dockerfile
    envVars:
      - key: DATABASE_URI
        value: <database-connection-string>
      - key: SECRET_KEY
        value: your_secret_key

  - type: web
    name: backend2
    plan: free
    env: docker
    dockerfilePath: ./backend_2/Dockerfile
    envVars:
      - key: DATABASE_URI
        value: <database-connection-string>

  - type: postgres
    name: db
    plan: free
    databaseName: mydatabase
    user: user
    password: password
