services:
  - name: frontend
    type: web
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: build
    routes:
      - type: redirect
        from: /
        to: https://frontend.onrender.com

  - name: backend1
    type: web
    env: docker
    plan: free
    dockerfilePath: ./backend_1/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase: mydatabase
      - key: SECRET_KEY
        value: your_secret_key

  - name: backend2
    type: web
    env: docker
    plan: free
    dockerfilePath: ./backend_2/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase: mydatabase

  - name: mydatabase
    type: database
    plan: free
    databaseName: mydatabase
    engine: postgres
    user: user
    password: password
    initialDatabase: mydatabase
